export let authorities = [
  "N/A",
  "Adur District Council",
  "Amber Valley Borough Council",
  "Arun District Council",
  "Ashfield District Council",
  "Ashford Borough Council",
  "Babergh District Council",
  "Barnsley Borough Council",
  "Basildon Borough Council",
  "Basingstoke & Deane Borough Council",
  "Bassetlaw District Council",
  "Bath and North East Somerset Council",
  "Bedford Borough Council",
  "Birmingham City Council",
  "Blaby District Council",
  "Blackburn with Darwen Borough Council",
  "Blackpool Council",
  "Bolsover District Council",
  "Bolton Borough Council",
  "Boston Borough Council",
  "Bournemouth, Christchurch and Poole Council",
  "Bracknell Forest Borough Council",
  "Bradford City Council",
  "Braintree District Council",
  "Breckland District Council",
  "Brentwood Borough Council",
  "Brighton and Hove City Council",
  "Bristol City Council",
  "Broadland District Council",
  "Bromsgrove District Council",
  "Broxbourne Borough Council",
  "Broxtowe Borough Council",
  "Buckinghamshire Council",
  "Burnley Borough Council",
  "Bury Borough Council",
  "Calderdale Borough Council",
  "Cambridge City Council",
  "Cambridgeshire and Peterborough Combined Authority",
  "Cambridgeshire County Council",
  "Cannock Chase District Council",
  "Canterbury City Council",
  "Castle Point District Council",
  "Central Bedfordshire Council",
  "Charnwood Borough Council",
  "Chelmsford City Council",
  "Cheltenham Borough Council",
  "Cherwell District Council",
  "Cheshire East Council",
  "Cheshire West and Chester Council",
  "Chesterfield Borough Council",
  "Chichester District Council",
  "Chorley Borough Council",
  "City of London Corporation",
  "City of York Council",
  "Colchester Borough Council",
  "Cornwall Council",
  "Cotswold District Council",
  "Coventry City Council",
  "Crawley Borough Council",
  "Cumberland Council",
  "Dacorum Borough Council",
  "Darlington Borough Council",
  "Dartford Borough Council",
  "Derby City Council",
  "Derbyshire County Council",
  "Derbyshire Dales District Council",
  "Devon County Council",
  "Doncaster Borough Council",
  "Dorset Council",
  "Dover District Council",
  "Dudley Borough Council",
  "Durham County Council",
  "East Cambridgeshire District Council",
  "East Devon District Council",
  "East Hampshire District Council",
  "East Hertfordshire District Council",
  "East Lindsey District Council",
  "East Riding of Yorkshire Council",
  "East Staffordshire Borough Council",
  "East Suffolk Council",
  "East Sussex County Council",
  "Eastbourne Borough Council",
  "Eastleigh Borough Council",
  "Elmbridge Borough Council",
  "Epping Forest District Council",
  "Epsom & Ewell Borough Council",
  "Erewash Borough Council",
  "Essex County Council",
  "Exeter City Council",
  "Fareham Borough Council",
  "Fenland District Council",
  "Folkestone and Hythe District Council",
  "Forest of Dean District Council",
  "Fylde Borough Council",
  "Gateshead Borough Council",
  "Gedling Borough Council",
  "Gloucester City Council",
  "Gloucestershire County Council",
  "Gosport Borough Council",
  "Gravesham Borough Council",
  "Great Yarmouth Borough Council",
  "Greater London Authority",
  "Greater Manchester Combined Authority",
  "Guildford Borough Council",
  "Halton Borough Council",
  "Hampshire County Council",
  "Harborough District Council",
  "Harlow District Council",
  "Hart District Council",
  "Hartlepool Borough Council",
  "Hastings Borough Council",
  "Havant Borough Council",
  "Herefordshire Council",
  "Hertfordshire County Council",
  "Hertsmere Borough Council",
  "High Peak Borough Council",
  "Hinckley and Bosworth Borough Council",
  "Horsham District Council",
  "Hull City Council",
  "Huntingdonshire District Council",
  "Hyndburn Borough Council",
  "Ipswich Borough Council",
  "Isle of Wight Council",
  "Kent County Council",
  "Kings Lynn & West Norfolk Borough Council",
  "Kirklees Borough Council",
  "Knowsley Borough Council",
  "Lancashire County Council",
  "Lancaster City Council",
  "Leeds City Council",
  "Leicester City Council",
  "Leicestershire County Council",
  "Lewes District Council",
  "Lichfield City Council",
  "Lincoln City Council",
  "Lincolnshire County Council",
  "Liverpool City Council",
  "Liverpool City Region Combined Authority",
  "London Borough of Barking and Dagenham",
  "London Borough of Barnet",
  "London Borough of Bexley",
  "London Borough of Brent",
  "London Borough of Bromley",
  "London Borough of Camden",
  "London Borough of Croydon",
  "London Borough of Ealing",
  "London Borough of Enfield",
  "London Borough of Hackney",
  "London Borough of Hammersmith and Fulham",
  "London Borough of Haringey",
  "London Borough of Harrow",
  "London Borough of Havering",
  "London Borough of Hillingdon",
  "London Borough of Hounslow",
  "London Borough of Islington",
  "Royal Borough of Kingston upon Thames",
  "Royal Borough of Greenwich",
  "Royal Borough of Kensington and Chelsea",
  "London Borough of Lambeth",
  "London Borough of Lewisham",
  "London Borough of Merton",
  "London Borough of Newham",
  "London Borough of Redbridge",
  "London Borough of Richmond upon Thames",
  "London Borough of Southwark",
  "London Borough of Sutton",
  "London Borough of Tower Hamlets",
  "London Borough of Waltham Forest",
  "London Borough of Wandsworth",
  "Westminster City Council",
  "Luton Borough Council",
  "Maidstone Borough Council",
  "Maldon District Council",
  "Malvern Hills District Council",
  "Manchester City Council",
  "Mansfield District Council",
  "Medway Council",
  "Melton Borough Council",
  "Mid Devon District Council",
  "Mid Suffolk District Council",
  "Mid Sussex District Council",
  "Middlesbrough Borough Council",
  "Milton Keynes Council",
  "Mole Valley District Council",
  "New Forest District Council",
  "Newark & Sherwood District Council",
  "Newcastle Upon Tyne City Council",
  "Newcastle-Under-Lyme Borough Council",
  "Norfolk County Council",
  "North Devon District Council",
  "North East Derbyshire District Council",
  "North East Joint Transport Committee",
  "North East Lincolnshire Council",
  "North Hertfordshire District Council",
  "North Kesteven District Council",
  "North Lincolnshire Council",
  "North Norfolk District Council",
  "North Northamptonshire Council",
  "North Somerset Council",
  "North Tyneside Borough Council",
  "North Warwickshire Borough Council",
  "North West Leicestershire District Council",
  "North Yorkshire Council",
  "Northern Ireland",
  "Northumberland County Council",
  "Norwich City Council",
  "Nottingham City Council",
  "Nottinghamshire County Council",
  "Nuneaton & Bedworth Borough Council",
  "Oadby & Wigston Borough Council",
  "Oldham Borough Council",
  "Oxford City Council",
  "Oxfordshire County Council",
  "Pendle Borough Council",
  "Peterborough City Council",
  "Plymouth City Council",
  "Portsmouth City Council",
  "Preston City Council",
  "Reading Borough Council",
  "Redcar and Cleveland Borough Council",
  "Redditch Borough Council",
  "Reigate & Banstead Borough Council",
  "Ribble Valley Borough Council",
  "Rochdale Borough Council",
  "Rochford District Council",
  "Rossendale Borough Council",
  "Rother District Council",
  "Rotherham Borough Council",
  "Rugby Borough Council",
  "Runnymede Borough Council",
  "Rushcliffe Borough Council",
  "Rushmoor Borough Council",
  "Rutland County Council",
  "Salford City Council",
  "Sandwell Borough Council",
  "Scotland",
  "Sefton Borough Council",
  "Sevenoaks District Council",
  "Sheffield City Council",
  "Shropshire Council",
  "Slough Borough Council",
  "Solihull Borough Council",
  "Somerset Council",
  "South Cambridgeshire District Council",
  "South Derbyshire District Council",
  "South Gloucestershire Council",
  "South Hams District Council",
  "South Holland District Council",
  "South Kesteven District Council",
  "South Norfolk District Council",
  "South Oxfordshire District Council",
  "South Ribble Borough Council",
  "South Staffordshire District Council",
  "South Tyneside Borough Council",
  "South Yorkshire Mayoral Combined Authority",
  "Southampton City Council",
  "Southend-on-Sea Borough Council",
  "Spelthorne Borough Council",
  "St Albans City Council",
  "St Helens Borough Council",
  "Stafford Borough Council",
  "Staffordshire County Council",
  "Staffordshire Moorlands District Council",
  "Stevenage Borough Council",
  "Stockport Borough Council",
  "Stockton-on-Tees Borough Council",
  "Stoke-on-Trent City Council",
  "Stratford on Avon District Council",
  "Stroud District Council",
  "Suffolk County Council",
  "Sunderland City Council",
  "Surrey County Council",
  "Surrey Heath Borough Council",
  "Swale Borough Council",
  "Swindon Borough Council",
  "Tameside Borough Council",
  "Tamworth Borough Council",
  "Tandridge District Council",
  "Tees Valley Combined Authority",
  "Teignbridge District Council",
  "Telford and Wrekin Borough Council",
  "Tendring District Council",
  "Test Valley Borough Council",
  "Tewkesbury Borough Council",
  "Thanet District Council",
  "The Council of the Isles of Scilly",
  "Three Rivers District Council",
  "Thurrock Council",
  "Tonbridge & Malling Borough Council",
  "Torbay Council",
  "Torridge District Council",
  "Trafford Borough Council",
  "Tunbridge Wells Borough Council",
  "Uttlesford District Council",
  "Vale of White Horse District Council",
  "Wakefield City Council",
  "Wales",
  "Walsall Borough Council",
  "Warrington Borough Council",
  "Warwick District Council",
  "Warwickshire County Council",
  "Watford Borough Council",
  "Waverley Borough Council",
  "Wealden District Council",
  "Welwyn Hatfield Borough Council",
  "West Berkshire Council",
  "West Devon District Council",
  "West Lancashire District Council",
  "West Lindsey District Council",
  "West Midlands Combined Authority",
  "West Northamptonshire Council",
  "West of England Combined Authority",
  "West Oxfordshire District Council",
  "West Suffolk Council",
  "West Sussex County Council",
  "West Yorkshire Combined Authority",
  "Westmorland and Furness Council",
  "Wigan Borough Council",
  "Wiltshire Council",
  "Winchester City Council",
  "Windsor and Maidenhead Borough Council",
  "Wirral Borough Council",
  "Woking Borough Council",
  "Wokingham Borough Council",
  "Wolverhampton City Council",
  "Worcester City Council",
  "Worcestershire County Council",
  "Worthing Borough Council",
  "Wychavon District Council ",
  "Wyre Borough Council",
  "Wyre Forest District Council",
];

export let transportOrCombinedAuthorities = [
  "Not applicable",
  "Cambridgeshire & Peterborough Combined Authority",
  "Greater Manchester Combined Authority",
  "Liverpool City Region Combined Authority",
  "North East Joint Transport Committee",
  "South Yorkshire Mayoral Combined Authority",
  "Tees Valley Combined Authority",
  "West Midlands Combined Authority",
  "West of England Combined Authority",
  "West Yorkshire Combined Authority",
];

export let regions = [
  "East of England",
  "East Midlands",
  "North East",
  "North West",
  "South East",
  "South West",
  "West Midlands",
  "Yorkshire and the Humber",
  "Other (please overtype this option)",
];

export let fundingProgrammes = [
  "Active Travel Fund",
  "Capability Fund",
  "City Region Sustainable Transport Settlements",
  "Levelling Up Fund",
  "Major Road Network",
  "Transforming Cities Fund",
  "Road Investment Strategy ",
  "Housing Infrastructure Fund",
  "National Cycle Network",
  "Other (please overtype this option)",
];

export let designStages = [
  "Feasibility",
  "Preliminary",
  "Outline design",
  "Detailed design",
  "Strategic business case",
  "Pre-outline business case",
  "Outline business case",
  "Final business case",
  "Other (please overtype this option)",
];
