// Deliberately separate from the one in $lib

export let criteria = [
  "Trip generation and assignment",
  "Active travel route audit",
  "Pedestrian access to local amenities",
  "Cycling accessibility",
  "Access to public transport",
  "Off-site transport infrastructure",
  "Site permeability",
  "Placemaking",
  "Cycle parking and trip-end facilities",
  "Travel planning",
];

export let localPlanningAuthorities = [
  "Adur",
  "Amber Valley",
  "Arun",
  "Ashfield",
  "Ashford",
  "Babergh",
  "Barnsley",
  "Basildon",
  "Basingstoke and Deane",
  "Bassetlaw",
  "Bath and North East Somerset",
  "Bedford",
  "Birmingham",
  "Blaby",
  "Blackburn with Darwen",
  "Blackpool",
  "Bolsover",
  "Bolton",
  "Boston",
  "Bournemouth, Christchurch and Poole",
  "Bracknell Forest",
  "Braintree",
  "Breckland",
  "Brentwood",
  "Brighton and Hove",
  "Bristol",
  "Broadland",
  "Broads Authority",
  "Bromsgrove",
  "Broxbourne",
  "Broxtowe",
  "Buckinghamshire",
  "Burnley",
  "Bury",
  "Calderdale",
  "Cambridge",
  "Cambridgeshire (County Matters)",
  "Cannock Chase",
  "Canterbury",
  "Castle Point",
  "Central Bedfordshire",
  "Charnwood",
  "Chelmsford",
  "Cheltenham",
  "Cherwell",
  "Cheshire East",
  "Cheshire West and Chester",
  "Chesterfield",
  "Chichester",
  "Chorley",
  "City of Bradford",
  "City of London",
  "City of Wolverhampton",
  "City of York",
  "Colchester",
  "Cornwall",
  "Cotswold",
  "Coventry",
  "Crawley",
  "Cumberland",
  "Dacorum",
  "Darlington",
  "Dartford",
  "Dartmoor National Park",
  "Derby",
  "Derbyshire (County Matters)",
  "Derbyshire Dales",
  "Devon (County Matters)",
  "Doncaster",
  "Dorset",
  "Dover",
  "Dudley",
  "Durham",
  "East Cambridgeshire",
  "East Devon",
  "East Hampshire",
  "East Hertfordshire",
  "East Lindsey",
  "East Riding of Yorkshire",
  "East Staffordshire",
  "East Suffolk",
  "East Sussex (County Matters)",
  "Eastbourne",
  "Eastleigh",
  "Ebbsfleet Development Corporation",
  "Elmbridge",
  "Epping Forest",
  "Epsom and Ewell",
  "Erewash",
  "Essex (County Matters)",
  "Exeter",
  "Exmoor National Park",
  "Fareham",
  "Fenland",
  "Folkestone and Hythe",
  "Forest of Dean",
  "Fylde",
  "Gateshead",
  "Gedling",
  "Gloucester",
  "Gloucestershire (County Matters)",
  "Gosport",
  "Gravesham",
  "Great Yarmouth",
  "Guildford",
  "Halton",
  "Hampshire (County Matters)",
  "Harborough",
  "Harlow",
  "Hart",
  "Hartlepool",
  "Hartlepool Development Corporation",
  "Hastings",
  "Havant",
  "Herefordshire",
  "Hertfordshire (County Matters)",
  "Hertsmere",
  "High Peak",
  "Hinckley and Bosworth",
  "Horsham",
  "Hull",
  "Huntingdonshire",
  "Hyndburn",
  "Ipswich",
  "Isle of Wight",
  "Isles of Scilly",
  "Kent (County Matters)",
  "King’s Lynn and West Norfolk",
  "Kirklees",
  "Knowsley",
  "Lake District National Park",
  "Lancashire (County Matters)",
  "Lancaster",
  "Leeds",
  "Leicester",
  "Leicestershire (County Matters)",
  "Lewes",
  "Lichfield",
  "Lincoln",
  "Lincolnshire (County Matters)",
  "Liverpool",
  "LB Barking and Dagenham",
  "LB Barnet",
  "LB Bexley",
  "LB Brent",
  "LB Bromley",
  "LB Camden",
  "LB Croydon",
  "LB Ealing",
  "LB Enfield",
  "LB Hackney",
  "LB Hammersmith and Fulham",
  "LB Haringey",
  "LB Harrow",
  "LB Havering",
  "LB Hillingdon",
  "LB Hounslow",
  "LB Islington",
  "LB Lambeth",
  "LB Lewisham",
  "LB Merton",
  "LB Newham",
  "LB Redbridge",
  "LB Richmond upon Thames",
  "LB Southwark",
  "LB Sutton",
  "LB Tower Hamlets",
  "LB Waltham Forest",
  "LB Wandsworth",
  "London Legacy Development Corporation",
  "Luton",
  "Maidstone",
  "Maldon",
  "Malvern Hills",
  "Manchester",
  "Mansfield",
  "Medway",
  "Melton",
  "Mid Devon",
  "Mid Suffolk",
  "Mid Sussex",
  "Middlesbrough",
  "Middlesbrough Development Corporation",
  "Milton Keynes",
  "Mole Valley",
  "New Forest",
  "New Forest National Park",
  "Newark and Sherwood",
  "Newcastle",
  "Newcastle-under-Lyme",
  "Norfolk (County Matters)",
  "North Devon",
  "North East Derbyshire",
  "North East Lincolnshire",
  "North Hertfordshire",
  "North Kesteven",
  "North Lincolnshire",
  "North Norfolk",
  "North Northamptonshire",
  "North Somerset",
  "North Tyneside",
  "North Warwickshire",
  "North West Leicestershire",
  "North York Moors National Park",
  "North Yorkshire",
  "Northumberland",
  "Northumberland National Park",
  "Norwich",
  "Nottingham",
  "Nottinghamshire (County Matters)",
  "Nuneaton and Bedworth",
  "Oadby and Wigston",
  "Old Oak and Park Royal Development Corporation",
  "Oldham",
  "Oxford",
  "Oxfordshire (County Matters)",
  "Peak District National Park",
  "Pendle",
  "Peterborough",
  "Planning Inspectorate (Section 62A applications)",
  "Plymouth",
  "Portsmouth",
  "Preston",
  "Reading",
  "Redcar and Cleveland",
  "Redditch",
  "Reigate and Banstead",
  "Ribble Valley",
  "Rochdale",
  "Rochford",
  "Rossendale",
  "Rother",
  "Rotherham",
  "RB Greenwich",
  "RB Kensington and Chelsea",
  "RB Kingston upon Thames",
  "RB Windsor and Maidenhead",
  "Rugby",
  "Runnymede",
  "Rushcliffe",
  "Rushmoor",
  "Rutland",
  "Salford",
  "Sandwell",
  "Sefton",
  "Sevenoaks",
  "Sheffield",
  "Shropshire",
  "Slough",
  "Solihull",
  "Somerset",
  "South Cambridgeshire",
  "South Derbyshire",
  "South Downs National Park",
  "South Gloucestershire",
  "South Hams",
  "South Holland",
  "South Kesteven",
  "South Norfolk",
  "South Oxfordshire",
  "South Ribble",
  "South Staffordshire",
  "South Tyneside",
  "Southampton",
  "Southend-on-Sea",
  "Spelthorne",
  "St Albans",
  "St Helens",
  "Stafford",
  "Staffordshire (County Matters)",
  "Staffordshire Moorlands",
  "Stevenage",
  "Stockport",
  "Stockton-on-Tees",
  "Stoke-on-Trent",
  "Stratford-on-Avon",
  "Stroud",
  "Suffolk (County Matters)",
  "Sunderland",
  "Surrey (County Matters)",
  "Surrey Heath",
  "Swale",
  "Swindon",
  "Tameside",
  "Tamworth",
  "Tandridge",
  "Teignbridge",
  "Telford and Wrekin",
  "Tendring",
  "Test Valley",
  "Tewkesbury",
  "Thanet",
  "Three Rivers",
  "Thurrock",
  "Tonbridge and Malling",
  "Torbay",
  "Torridge",
  "Trafford",
  "Tunbridge Wells",
  "Uttlesford",
  "Vale of White Horse",
  "Wakefield",
  "Walsall",
  "Warrington",
  "Warwick",
  "Warwickshire (County Matters)",
  "Watford",
  "Waverley",
  "Wealden",
  "Welwyn Hatfield",
  "West Berkshire",
  "West Devon",
  "West Lancashire",
  "West Lindsey",
  "West Northamptonshire",
  "West Oxfordshire",
  "West Suffolk",
  "West Sussex (County Matters)",
  "Westminster",
  "Westmorland and Furness",
  "Wigan",
  "Wiltshire",
  "Winchester",
  "Wirral",
  "Woking",
  "Wokingham",
  "Worcester",
  "Worcestershire (County Matters)",
  "Worthing",
  "Wychavon",
  "Wyre",
  "Wyre Forest",
  "Yorkshire Dales National Park",
];

export let localHighwayAuthorities = [
  "Barnsley",
  "Bath and North East Somerset",
  "Bedford",
  "Birmingham",
  "Blackburn with Darwen",
  "Blackpool",
  "Bolton",
  "Bournemouth, Christchurch and Poole",
  "Bracknell Forest",
  "Brighton and Hove",
  "Bristol",
  "Buckinghamshire",
  "Bury",
  "Calderdale",
  "Cambridgeshire",
  "Central Bedfordshire",
  "Cheshire East",
  "Cheshire West and Chester",
  "City of Bradford",
  "City of London",
  "City of Wolverhampton",
  "City of York",
  "Cornwall",
  "Coventry",
  "Cumberland",
  "Darlington",
  "Derby",
  "Derbyshire",
  "Devon",
  "Doncaster",
  "Dorset",
  "Dudley",
  "Durham",
  "East Riding of Yorkshire",
  "East Sussex",
  "Essex",
  "Gateshead",
  "Gloucestershire",
  "Halton",
  "Hampshire",
  "Hartlepool",
  "Herefordshire",
  "Hertfordshire",
  "Hull",
  "Isle of Wight",
  "Isles of Scilly",
  "Kent",
  "Kirkless",
  "Knowsley",
  "Lancashire",
  "Leeds",
  "Leicester",
  "Leicestershire",
  "Lincolnshire",
  "Liverpool",
  "LB Barking and Dagenham",
  "LB Barnet",
  "LB Bexley",
  "LB Brent",
  "LB Bromley",
  "LB Camden",
  "LB Croydon",
  "LB Ealing",
  "LB Enfield",
  "LB Hackney",
  "LB Hammersmith and Fulham",
  "LB Haringey",
  "LB Harrow",
  "LB Havering",
  "LB Hillingdon",
  "LB Hounslow",
  "LB Islington",
  "LB Lambeth",
  "LB Lewisham",
  "LB Merton",
  "LB Newham",
  "LB Redbridge",
  "LB Richmond upon Thames",
  "LB Southwark",
  "LB Sutton",
  "LB Tower Hamlets",
  "LB Waltham Forest",
  "LB Wandsworth",
  "Luton",
  "Manchester",
  "Medway",
  "Middlesbrough",
  "Milton Keynes",
  "Newcastle",
  "Norfolk",
  "North East Lincolnshire",
  "North Lincolnshire",
  "North Northamptonshire",
  "North Somerset",
  "North Tyneside",
  "North Yorkshire",
  "Northumberland",
  "Nottingham",
  "Nottinghamshire",
  "Oldham",
  "Oxfordshire",
  "Peterborough",
  "Plymouth",
  "Portsmouth",
  "Reading",
  "Redcar and Cleveland",
  "Rochdale",
  "Rotherham",
  "RB Greenwich",
  "RB Kensington and Chelsea",
  "RB Kingston upon Thames",
  "RB Windsor and Maidenhead",
  "Rutland",
  "Salford",
  "Sandwell",
  "Sefton",
  "Sheffield",
  "Shropshire",
  "Slough",
  "Solihull",
  "Somerset",
  "South Gloucestershire",
  "South Tyneside",
  "Southampton",
  "Southend-on-Sea",
  "St Helens",
  "Staffordshire",
  "Stockport",
  "Stockton-on-Tees",
  "Stoke-on-Trent",
  "Suffolk",
  "Sunderland",
  "Surrey",
  "Swindon",
  "Tameside",
  "Telford and Wrekin",
  "Thurrock",
  "Torbay",
  "Trafford",
  "Wakefield",
  "Walsall",
  "Warrington",
  "Warwickshire",
  "West Berkshire",
  "West Northamptonshire",
  "West Sussex",
  "Westminster",
  "Westmorland and Furness",
  "Wigan",
  "Wiltshire",
  "Wirral",
  "Wokingham",
  "Worcestershire",
];

export let applicationTypes = [
  "Pre-application enquiry",
  "Full planning permission",
  "Outline planning permission",
  "Hybrid planning permission",
  "Reserved matters",
  "Discharge of condition(s)",
  "Removal / Variation of condition(s)",
  "Other",
];
